
name: Called Workflow for Selenium Test

on:
  workflow_call:
    inputs:
     username:
      required: true
      type: string
    secrets:
      token:
        required: true

jobs:
  selenium_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    
    - name: Build with Maven
      run: mvn -B clean test
